### ISSUE TITLE
Saving space by using smaller VARCHAR?

### ISSUE THREAD

**Issue by ChristianGfK** [EXASOL/database-migration#4]
Hi,

what exactly is there to gain from using smaller VARCHAR fields, as [the convert datatypes script suggests](https://github.com/exasol/database-migration/tree/master/post_load_optimization#optimize-datatypes)?
[The Exasol documentation says](https://docs.exasol.com/sql_references/data_types/datatypedetails.htm) _"These strings are stored in their respective length."_, so I would assume there is no space to be saved here?

If not that, then... what is the gain?

Best regards
Christian

**Comment by exaValerieWiedemann** [comment]
Hi Christian,
you're right, the storage used is not impacted. But, if you consider import/export or access from tools via odbc/jdbc you will lose performance if you choose a VARCHAR(2000000) because the buffers would be allocated with maximum size. You can also observe that e.g. Tableau displays a VARCHAR different if you set it to VARCHAR(2000000) compared to a VARCHAR(50), the VARCHAR(2000000) column is cut off after 15 characters while the VARCHAR(50) is displayed completely:
![grafik](https://user-images.githubusercontent.com/35218717/62620833-95801c00-b91a-11e9-82b8-945aa2ba6113.png)


The second aspect (which might be a matter of personal taste) is that it's easier to understand what to expect in a certain field if the VARCHAR size is set properly. So if the column is a VARCHAR(100), you know that you can expect something compact as a result of your query.

I hope this answers your question,
Valerie

**Comment by ChristianGfK** [comment]
Hi Valerie,

yes, thank you for the explanation. 👍 

Best regards
Christian
